// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHSoMZ74NFDp8-qW7RT6CKrD0KxccdUws',
    appId: '1:1077130966408:web:51065a7a5b014888aab63d',
    messagingSenderId: '1077130966408',
    projectId: 'gtco-smart-invoice',
    authDomain: 'gtco-smart-invoice.firebaseapp.com',
    storageBucket: 'gtco-smart-invoice.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvUvFW2qgAnxX1nHUgiXn2h5af6XE-VWo',
    appId: '1:1077130966408:android:b1b451a7035deb60aab63d',
    messagingSenderId: '1077130966408',
    projectId: 'gtco-smart-invoice',
    storageBucket: 'gtco-smart-invoice.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_0GdIiMbQ3RrSSs8Pk4WA7oUxrvi-_WI',
    appId: '1:1077130966408:ios:e3210e5cb6b5d620aab63d',
    messagingSenderId: '1077130966408',
    projectId: 'gtco-smart-invoice',
    storageBucket: 'gtco-smart-invoice.firebasestorage.app',
    iosBundleId: 'com.gtco.smart-invoice',
  );
}
